# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cafe_pb2 as cafe__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cafe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CafeStub(object):
    """Definisco il servizio cafe, che deve mettere a disposizione due stream:
    Uno di richiesta per il client ed uno di risposta per il server

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderStream = channel.stream_stream(
                '/cafe.Cafe/OrderStream',
                request_serializer=cafe__pb2.OrderRequest.SerializeToString,
                response_deserializer=cafe__pb2.OrderResponse.FromString,
                _registered_method=True)


class CafeServicer(object):
    """Definisco il servizio cafe, che deve mettere a disposizione due stream:
    Uno di richiesta per il client ed uno di risposta per il server

    """

    def OrderStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CafeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderStream': grpc.stream_stream_rpc_method_handler(
                    servicer.OrderStream,
                    request_deserializer=cafe__pb2.OrderRequest.FromString,
                    response_serializer=cafe__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafe.Cafe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cafe.Cafe', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cafe(object):
    """Definisco il servizio cafe, che deve mettere a disposizione due stream:
    Uno di richiesta per il client ed uno di risposta per il server

    """

    @staticmethod
    def OrderStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cafe.Cafe/OrderStream',
            cafe__pb2.OrderRequest.SerializeToString,
            cafe__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
